import { createSlice } from '@reduxjs/toolkit';

// Define the initial state for the user
const initialState = {
  isLoggedIn: false,
  userDetails: {},
};

// Create the slice
const userSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    login(state, action) {
      state.isLoggedIn = true;
      state.userDetails = action.payload;
    },
    logout(state) {
      state.isLoggedIn = false;
      state.userDetails = {};
    },
  },
});

// Export the actions generated by the slice
export const { login, logout } = userSlice.actions;

// Export the reducer as the default export
export default userSlice.reducer;
